spring.application.name=scm
server.port=8080

# data base config
spring.datasource.url=jdbc:mysql://localhost:3306/scm
spring.datasource.username=root
spring.datasource.password=Betu8959@

# hibernate config
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.devtools.restart.enabled=false